package igym.entities;

import jakarta.persistence.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.*;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import igym.entities.enums.Status;

/**
 * Represents a workout plan, containing a list of exercises performed together,
 * and associated with a gym.
 * 
 * <p>
 * Each workout maintains a one-to-many relationship with exercises, and a
 * many-to-one relationship with a gym.
 * Field-level validations ensure that each workout has a valid name and at
 * least one exercise.
 * </p>
 *
 * <p>
 * Lombok is used to generate getters and setters. The {@code id} field uses
 * {@code @Setter(AccessLevel.NONE)}
 * to prevent manual assignment, as it is automatically generated by the
 * database.
 * </p>
 */

@Entity
@Getter
@Setter
@NoArgsConstructor
public class Workout {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Setter(AccessLevel.NONE)
    private UUID id;

    @NotBlank(message = "Workout name is required")
    @Column(nullable = false, length = 50)
    @Size(min = 1, max = 50, message = "Name must be between 3 and 50 characters")
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status = Status.active;

    @UpdateTimestamp
    private Instant updated_at;

    @NotEmpty(message = "Workout must contain at least one exercise")
    @OneToMany(mappedBy = "workout", cascade = CascadeType.ALL)
    @Valid
    @JsonManagedReference
    private List<Exercise> exerciseList;

    @ManyToOne(optional = false)
    @JoinColumn(name = "gym_id", nullable = false)
    @JsonBackReference
    private Gym gym;

    @UpdateTimestamp
    private Instant updated_at;
}
